# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'weather.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\x12\x07weather\"\x8a\x01\n\x04Grid\x12\x10\n\x08variable\x18\x01 \x01(\t\x12\n\n\x02nx\x18\x02 \x01(\x05\x12\n\n\x02ny\x18\x03 \x01(\x05\x12\x0e\n\x06values\x18\x04 \x03(\x02\x12\x11\n\tlat_start\x18\x05 \x01(\x02\x12\x11\n\tlon_start\x18\x06 \x01(\x02\x12\x10\n\x08lat_step\x18\x07 \x01(\x02\x12\x10\n\x08lon_step\x18\x08 \x01(\x02\"\x99\x01\n\x05Point\x12\x12\n\nstation_id\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x02\x12\x0b\n\x03lon\x18\x03 \x01(\x02\x12\x30\n\tvariables\x18\x04 \x03(\x0b\x32\x1d.weather.Point.VariablesEntry\x1a\x30\n\x0eVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"-\n\x08Geometry\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x13\n\x0b\x63oordinates\x18\x02 \x03(\x02\"v\n\x0fWeatherResponse\x12\x1c\n\x05grids\x18\x01 \x03(\x0b\x32\r.weather.Grid\x12\x1e\n\x06points\x18\x02 \x03(\x0b\x32\x0e.weather.Point\x12%\n\ngeometries\x18\x03 \x03(\x0b\x32\x11.weather.Geometryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT_VARIABLESENTRY']._loaded_options = None
  _globals['_POINT_VARIABLESENTRY']._serialized_options = b'8\001'
  _globals['_GRID']._serialized_start=27
  _globals['_GRID']._serialized_end=165
  _globals['_POINT']._serialized_start=168
  _globals['_POINT']._serialized_end=321
  _globals['_POINT_VARIABLESENTRY']._serialized_start=273
  _globals['_POINT_VARIABLESENTRY']._serialized_end=321
  _globals['_GEOMETRY']._serialized_start=323
  _globals['_GEOMETRY']._serialized_end=368
  _globals['_WEATHERRESPONSE']._serialized_start=370
  _globals['_WEATHERRESPONSE']._serialized_end=488
# @@protoc_insertion_point(module_scope)
